@baseUrl = http://localhost:3000/users
@json = application/json

### Register
POST {{baseUrl}}/register
Content-Type: {{json}}

{
  "name": "Test User",
  "email": "test@email.com",
  "password": "123456",
  "password_confirmation": "123456",
  "birth": "2008-01-01",
  "occupation": "Student"
}

### Login
POST {{baseUrl}}/login
Content-Type: {{json}}

{
  "email": "estevan.zimermann@gmail.com",
  "password": "admin"
}

> {%
  client.global.set("token", response.body.token);
%}
# sets the token globally so it can be used by other rest files

### Recover password
POST {{baseUrl}}/password/recover
Content-Type: {{json}}

{
  "email": "estevan.zimermann@gmail.com"
}
