@baseUrl = http://localhost:3000/users
@json = application/json

### Register
POST {{baseUrl}}/register
Content-Type: {{json}}

{
  "name": "Test User",
  "email": "test@email.com",
  "password": "123456",
  "password_confirmation": "123456",
  "birth": "2008-01-01",
  "occupation": "Student"
}

### Login
POST {{baseUrl}}/login
Content-Type: {{json}}

{
  "email": "estevan.zimermann@gmail.com",
  "password": "admin"
}

### Recover password
POST {{baseUrl}}/password/recover
Content-Type: {{json}}

{
  "email": "estevan.zimermann@gmail.com"
}

### Update password
POST {{baseUrl}}/password/update
Content-Type: {{json}}

{
  "password": "admin2",
  "password_confirmation": "admin2",
  "token": "29c70bf52e6cda5ca2b0df366956b898e1e33c70",//manually added token
}
