@baseUrl = http://localhost:3000/users
@json = application/json
@token = {{token}}

### Get blog
GET {{baseUrl}}/1

### Get followers
GET {{baseUrl}}/followers/1

### Get members
GET {{baseUrl}}/members/1

### Get posts
GET {{baseUrl}}/posts/1

### Get requests
GET {{baseUrl}}/requests/1
Authorization: Bearer {{token}}

### Delete notification
DELETE {{baseUrl}}/notifications/destroy/1
Authorization: Bearer {{token}}

### Store preferences
POST {{baseUrl}}/preferences/store
Authorization: Bearer {{token}}
Content-Type: {{json}}

{
  "dark_mode": true
}

### Update user
PUT {{baseUrl}}/update
Authorization: Bearer {{token}}
Content-Type: {{json}}

{
  "name": "Updated Name"
}

### Update photo
PUT {{baseUrl}}/update/photo
Authorization: Bearer {{token}}
Content-Type: multipart/form-data

< ./avatar.png
