@baseUrl = http://localhost:3000/users
@json = application/json
@token = {{token}}

### Get blog
GET {{baseUrl}}/1

### Get followers
GET {{baseUrl}}/followers/1

### Get members
GET {{baseUrl}}/members/1

### Get posts
GET {{baseUrl}}/posts/1

### Get requests
GET {{baseUrl}}/requests/1
Authorization: Bearer {{token}}

### Post Send membership request
POST {{baseUrl}}/members/request/send/1
Authorization: Bearer {{token}}

### Post Accept membership request
POST {{baseUrl}}/members/request/accept/1
Authorization: Bearer {{token}}

### Post Follow/Unfollow blog
POST {{baseUrl}}/follow/1
Authorization: Bearer {{token}}

### Register Blog
POST {{baseUrl}}/store
Authorization: Bearer {{token}}
Content-Type: {{json}}

{
  "name": "Blog name test",
  "subname": "blog subname test",
  "description": "lorem ipsum random blog test description",
  "category": "Technology"
}

### Update
PUT {{baseUrl}}/update
Authorization: Bearer {{token}}
Content-Type: {{json}}

{
  "id": 1,
  "name": "Blog update test",
  "subname": "Blog subname update test",
  "description": "Blog description update test",
  "category": "Category_test"
}

### Update photo
PUT {{baseUrl}}/update/photo
Authorization: Bearer {{token}}
Content-Type: multipart/form-data

< ./avatar.png

### Update photo
PUT {{baseUrl}}/update/banner
Authorization: Bearer {{token}}
Content-Type: multipart/form-data

< ./avatar.png

### Delete member
DELETE {{baseUrl}}/members/destroy/1
Authorization: Bearer {{token}}

### Delete blog
DELETE {{baseUrl}}/destroy/1
Authorization: Bearer {{token}}
