@baseUrl = http://localhost:3000/posts
@json = application/json
@token = {{token}}

### Get post
GET {{baseUrl}}/view/1

### Get search
GET {{baseUrl}}/search

### Get home
GET {{baseUrl}}/home

### Get popular
GET {{baseUrl}}/popular

### Get recents
GET {{baseUrl}}/recents

### Get topics
GET {{baseUrl}}/topics

### Get trending list
GET {{baseUrl}}/list/trending

### Get recents list
GET {{baseUrl}}/list/recents

### Get user posts
GET {{baseUrl}}/list/following/1

### Get user keywords
GET {{baseUrl}}/list/keyword/1

### Get user post history
GET {{baseUrl}}/list/history
Authorization: Bearer {{token}}


### Comments store
POST {{baseUrl}}/comments/store
Authorization: Bearer {{token}}
Content-Type: {{json}}

{
  "content": "Comment test",
  "post_id": 1
}

### Post store
POST {{baseUrl}}/store
Authorization: Bearer {{token}}
Content-Type: {{json}}

{
  "title": "Title test",
  "subtitle": "Subtitle test",
  "summary": "summary test",
  "blog_id": 1,
  "contents": [],
  "tags": []
}


### Post like/unlike
POST {{baseUrl}}/like/1
Authorization: Bearer {{token}}

### Post image pre-upload
POST {{baseUrl}}/image/upload
Authorization: Bearer {{token}}

### Comment update
PUT {{baseUrl}}/comments/update
Authorization: Bearer {{token}}
Content-Type: {{json}}

{
  "id": 1,
  "content": "Comment update test",
}

### Post update
PUT {{baseUrl}}/update
Authorization: Bearer {{token}}
Content-Type: {{json}}

{
  "post_id": 1,
  "title": "Title test",
  "subtitle": "Subtitle test",
  "summary": "Summary test",
  "contents": [],
  "tags": []
}

### Delete post comment
DELETE {{baseUrl}}/comments/destroy/1
Authorization: Bearer {{token}}

### Post delete
DELETE {{baseUrl}}/destroy/1
Authorization: Bearer {{token}}
