@baseUrl = http://localhost:3000/users
// Manually added token
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzcwMjk4ODU2LCJleHAiOjE3NzAzODUyNTZ9.8cLTkFZMfUVKj_mnBnfOh7aXiPBrfIJc3g8B3oghYx0

### Store preferences
POST {{baseUrl}}/preferences/store
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "dark_mode": true
}
