@baseUrl = http://localhost:3000/users
@json = application/json
@token = {{token}}

### Get profile
GET {{baseUrl}}/profile/1

### Dark mode
GET {{baseUrl}}/dark
Authorization: Bearer {{token}}

### Get following
GET {{baseUrl}}/following/1

### User membering
GET {{baseUrl}}/membering/1

### Member requests
GET {{baseUrl}}/requests/1
Authorization: Bearer {{token}}

### Get notifications
GET {{baseUrl}}/notifications/1
Authorization: Bearer {{token}}

### Delete notification
DELETE {{baseUrl}}/notifications/destroy/1
Authorization: Bearer {{token}}

### Delete all notifications
DELETE {{baseUrl}}/notifications/destroy/all
Authorization: Bearer {{token}}

### User posts
GET {{baseUrl}}/posts/1

### Store preferences
POST {{baseUrl}}/preferences/store
Authorization: Bearer {{token}}
Content-Type: {{json}}

{
  "dark_mode": true
}

### User searches
GET {{baseUrl}}/searches
Authorization: Bearer {{token}}

### Delete search
DELETE {{baseUrl}}/searches/destroy/1
Authorization: Bearer {{token}}

### Update user
PUT {{baseUrl}}/update
Authorization: Bearer {{token}}
Content-Type: {{json}}

{
  "name": "Updated Name"
}

### Update photo
PUT {{baseUrl}}/update/photo
Authorization: Bearer {{token}}
Content-Type: multipart/form-data

< ./avatar.png

### Update banner
PUT {{baseUrl}}/update/banner
Authorization: Bearer {{token}}
Content-Type: multipart/form-data

< ./banner.png

### Delete user
DELETE {{baseUrl}}/1
Authorization: Bearer {{token}}
